import { POSVerb } from "@ezl-types";

export const verbs: POSVerb[] = [
  {
    partOfSpeech: "verb",
    lemma: "flirten",
    pastParticiple: "geflirtet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to flirt",
  },
  {
    partOfSpeech: "verb",
    lemma: "anmachen",
    pastParticiple: "angemacht",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to hit on",
  },
  {
    partOfSpeech: "verb",
    lemma: "anlächeln",
    pastParticiple: "angelächelt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to smile at",
  },
  {
    partOfSpeech: "verb",
    lemma: "zwinkern",
    pastParticiple: "gezwinkert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to wink",
  },
  {
    partOfSpeech: "verb",
    lemma: "anschauen",
    pastParticiple: "angeschaut",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to look at",
  },
  {
    partOfSpeech: "verb",
    lemma: "beobachten",
    pastParticiple: "beobachtet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to observe",
  },
  {
    partOfSpeech: "verb",
    lemma: "reden",
    pastParticiple: "geredet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to talk",
  },
  {
    partOfSpeech: "verb",
    lemma: "sprechen",
    pastParticiple: "gesprochen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to speak",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich unterhalten",
    pastParticiple: "sich unterhalten",
    isReflexive: true,
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to converse",
  },
  {
    partOfSpeech: "verb",
    lemma: "kennenlernen",
    pastParticiple: "kennengelernt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to get to know",
  },
  {
    partOfSpeech: "verb",
    lemma: "treffen",
    pastParticiple: "getroffen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to meet",
  },
  {
    partOfSpeech: "verb",
    lemma: "berühren",
    pastParticiple: "berührt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to touch",
  },
  {
    partOfSpeech: "verb",
    lemma: "umarmen",
    pastParticiple: "umarmt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to hug",
  },
  {
    partOfSpeech: "verb",
    lemma: "küssen",
    pastParticiple: "geküsst",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to kiss",
  },
  {
    partOfSpeech: "verb",
    lemma: "komplimentieren",
    pastParticiple: "komplimentiert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to compliment",
  },
  {
    partOfSpeech: "verb",
    lemma: "schmeicheln",
    pastParticiple: "geschmeichelt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to flatter",
  },
  {
    partOfSpeech: "verb",
    lemma: "lachen",
    pastParticiple: "gelacht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to laugh",
  },
  {
    partOfSpeech: "verb",
    lemma: "lachen über",
    pastParticiple: "gelacht über",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to laugh about",
  },
  {
    partOfSpeech: "verb",
    lemma: "necken",
    pastParticiple: "geneckt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to tease",
  },
  {
    partOfSpeech: "verb",
    lemma: "ärgern",
    pastParticiple: "geärgert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to annoy",
  },
  {
    partOfSpeech: "verb",
    lemma: "fragen",
    pastParticiple: "gefragt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to ask",
  },
  {
    partOfSpeech: "verb",
    lemma: "einladen",
    pastParticiple: "eingeladen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to invite",
  },
  {
    partOfSpeech: "verb",
    lemma: "ausgehen",
    pastParticiple: "ausgegangen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to go out",
  },
  {
    partOfSpeech: "verb",
    lemma: "daten",
    pastParticiple: "gedatet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to date",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich verabreden",
    pastParticiple: "sich verabredet",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to make a date",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich verlieben",
    pastParticiple: "sich verliebt",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to fall in love",
  },
  {
    partOfSpeech: "verb",
    lemma: "lieben",
    pastParticiple: "geliebt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to love",
  },
  {
    partOfSpeech: "verb",
    lemma: "mögen",
    pastParticiple: "gemocht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to like",
  },
  {
    partOfSpeech: "verb",
    lemma: "genießen",
    pastParticiple: "genossen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to enjoy",
  },
  {
    partOfSpeech: "verb",
    lemma: "verführen",
    pastParticiple: "verführt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to seduce",
  },
];
