import { POSVerb } from "@ezl-types";

export enum VocabularyTopics {
  GroceryShopping = "grocery shopping",
  Flirting = "flirting",
  SportsAndExercise = "sports and exercise",
  GettingAround = "getting around",
  FoodAndDrink = "food and drink",
}

const shoppingVerbs: POSVerb[] = [
  {
    partOfSpeech: "verb",
    lemma: "einkaufen",
    pastParticiple: "eingekauft",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to shop",
  },
  {
    partOfSpeech: "verb",
    lemma: "kaufen",
    pastParticiple: "gekauft",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to buy",
  },
  {
    partOfSpeech: "verb",
    lemma: "verkaufen",
    pastParticiple: "verkauft",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to sell",
  },
  {
    partOfSpeech: "verb",
    lemma: "brauchen",
    pastParticiple: "gebraucht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to need",
  },
  {
    partOfSpeech: "verb",
    lemma: "suchen",
    pastParticiple: "gesucht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to look for",
  },
  {
    partOfSpeech: "verb",
    lemma: "finden",
    pastParticiple: "gefunden",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to find",
  },
  {
    partOfSpeech: "verb",
    lemma: "wählen",
    pastParticiple: "gewählt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to choose",
  },
  {
    partOfSpeech: "verb",
    lemma: "aussuchen",
    pastParticiple: "ausgesucht",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to select",
  },
  {
    partOfSpeech: "verb",
    lemma: "bezahlen",
    pastParticiple: "bezahlt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pay",
  },
  {
    partOfSpeech: "verb",
    lemma: "kosten",
    pastParticiple: "gekostet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cost",
  },
  {
    partOfSpeech: "verb",
    lemma: "wiegen",
    pastParticiple: "gewogen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to weigh",
  },
  {
    partOfSpeech: "verb",
    lemma: "vergleichen",
    pastParticiple: "verglichen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to compare",
  },
  {
    partOfSpeech: "verb",
    lemma: "anbieten",
    pastParticiple: "angeboten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to offer",
  },
  {
    partOfSpeech: "verb",
    lemma: "reduzieren",
    pastParticiple: "reduziert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to reduce",
  },
  {
    partOfSpeech: "verb",
    lemma: "sparen",
    pastParticiple: "gespart",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to save",
  },
  {
    partOfSpeech: "verb",
    lemma: "bestellen",
    pastParticiple: "bestellt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to order",
  },
  {
    partOfSpeech: "verb",
    lemma: "abholen",
    pastParticiple: "abgeholt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pick up",
  },
  {
    partOfSpeech: "verb",
    lemma: "liefern",
    pastParticiple: "geliefert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to deliver",
  },
  {
    partOfSpeech: "verb",
    lemma: "einpacken",
    pastParticiple: "eingepackt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pack",
  },
  {
    partOfSpeech: "verb",
    lemma: "auspacken",
    pastParticiple: "ausgepackt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to unpack",
  },
  {
    partOfSpeech: "verb",
    lemma: "probieren",
    pastParticiple: "probiert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to try",
  },
  {
    partOfSpeech: "verb",
    lemma: "anfassen",
    pastParticiple: "angefasst",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to touch",
  },
  {
    partOfSpeech: "verb",
    lemma: "untersuchen",
    pastParticiple: "untersucht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to examine",
  },
  {
    partOfSpeech: "verb",
    lemma: "merken",
    pastParticiple: "gemerkt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to notice",
  },
  {
    partOfSpeech: "verb",
    lemma: "behalten",
    pastParticiple: "behalten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to keep",
  },
  {
    partOfSpeech: "verb",
    lemma: "verlieren",
    pastParticiple: "verloren",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to lose",
  },
  {
    partOfSpeech: "verb",
    lemma: "bekommen",
    pastParticiple: "bekommen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to get",
  },
  {
    partOfSpeech: "verb",
    lemma: "geben",
    pastParticiple: "gegeben",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to give",
  },
  {
    partOfSpeech: "verb",
    lemma: "nehmen",
    pastParticiple: "genommen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to take",
  },
  {
    partOfSpeech: "verb",
    lemma: "zeigen",
    pastParticiple: "gezeigt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to show",
  },
  {
    partOfSpeech: "verb",
    lemma: "fragen",
    pastParticiple: "gefragt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to ask",
  },
  {
    partOfSpeech: "verb",
    lemma: "wünschen",
    pastParticiple: "gewünscht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to wish",
  },
  {
    partOfSpeech: "verb",
    lemma: "empfehlen",
    pastParticiple: "empfohlen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to recommend",
  },
  {
    partOfSpeech: "verb",
    lemma: "wiegen",
    pastParticiple: "gewogen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to weigh",
  },
  {
    partOfSpeech: "verb",
    lemma: "lagern",
    pastParticiple: "gelagert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to store",
  },
  {
    partOfSpeech: "verb",
    lemma: "auswählen",
    pastParticiple: "ausgewählt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to select",
  },
  {
    partOfSpeech: "verb",
    lemma: "abwiegen",
    pastParticiple: "abgewogen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to weigh out",
  },
  {
    partOfSpeech: "verb",
    lemma: "prüfen",
    pastParticiple: "geprüft",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to check",
  },
  {
    partOfSpeech: "verb",
    lemma: "kosten",
    pastParticiple: "gekostet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to taste",
  },
  {
    partOfSpeech: "verb",
    lemma: "schneiden",
    pastParticiple: "geschnitten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cut",
  },
  {
    partOfSpeech: "verb",
    lemma: "schälen",
    pastParticiple: "geschält",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to peel",
  },
  {
    partOfSpeech: "verb",
    lemma: "waschen",
    pastParticiple: "gewaschen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to wash",
  },
  {
    partOfSpeech: "verb",
    lemma: "putzen",
    pastParticiple: "geputzt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to clean",
  },
  {
    partOfSpeech: "verb",
    lemma: "zubereiten",
    pastParticiple: "zubereitet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to prepare",
  },
  {
    partOfSpeech: "verb",
    lemma: "kochen",
    pastParticiple: "gekocht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cook",
  },
  {
    partOfSpeech: "verb",
    lemma: "backen",
    pastParticiple: "gebacken",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to bake",
  },
  {
    partOfSpeech: "verb",
    lemma: "braten",
    pastParticiple: "gebraten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to fry",
  },
  {
    partOfSpeech: "verb",
    lemma: "servieren",
    pastParticiple: "serviert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to serve",
  },
  {
    partOfSpeech: "verb",
    lemma: "essen",
    pastParticiple: "gegessen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to eat",
  },
  {
    partOfSpeech: "verb",
    lemma: "trinken",
    pastParticiple: "getrunken",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to drink",
  },
];

const flirtingVerbs: POSVerb[] = [
  {
    partOfSpeech: "verb",
    lemma: "flirten",
    pastParticiple: "geflirtet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to flirt",
  },
  {
    partOfSpeech: "verb",
    lemma: "anmachen",
    pastParticiple: "angemacht",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to hit on",
  },
  {
    partOfSpeech: "verb",
    lemma: "anlächeln",
    pastParticiple: "angelächelt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to smile at",
  },
  {
    partOfSpeech: "verb",
    lemma: "zwinkern",
    pastParticiple: "gezwinkert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to wink",
  },
  {
    partOfSpeech: "verb",
    lemma: "anschauen",
    pastParticiple: "angeschaut",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to look at",
  },
  {
    partOfSpeech: "verb",
    lemma: "beobachten",
    pastParticiple: "beobachtet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to observe",
  },
  {
    partOfSpeech: "verb",
    lemma: "reden",
    pastParticiple: "geredet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to talk",
  },
  {
    partOfSpeech: "verb",
    lemma: "sprechen",
    pastParticiple: "gesprochen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to speak",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich unterhalten",
    pastParticiple: "sich unterhalten",
    isReflexive: true,
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to converse",
  },
  {
    partOfSpeech: "verb",
    lemma: "kennenlernen",
    pastParticiple: "kennengelernt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to get to know",
  },
  {
    partOfSpeech: "verb",
    lemma: "treffen",
    pastParticiple: "getroffen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to meet",
  },
  {
    partOfSpeech: "verb",
    lemma: "berühren",
    pastParticiple: "berührt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to touch",
  },
  {
    partOfSpeech: "verb",
    lemma: "umarmen",
    pastParticiple: "umarmt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to hug",
  },
  {
    partOfSpeech: "verb",
    lemma: "küssen",
    pastParticiple: "geküsst",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to kiss",
  },
  {
    partOfSpeech: "verb",
    lemma: "komplimentieren",
    pastParticiple: "komplimentiert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to compliment",
  },
  {
    partOfSpeech: "verb",
    lemma: "schmeicheln",
    pastParticiple: "geschmeichelt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to flatter",
  },
  {
    partOfSpeech: "verb",
    lemma: "lachen",
    pastParticiple: "gelacht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to laugh",
  },
  {
    partOfSpeech: "verb",
    lemma: "lachen über",
    pastParticiple: "gelacht über",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to laugh about",
  },
  {
    partOfSpeech: "verb",
    lemma: "necken",
    pastParticiple: "geneckt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to tease",
  },
  {
    partOfSpeech: "verb",
    lemma: "ärgern",
    pastParticiple: "geärgert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to annoy",
  },
  {
    partOfSpeech: "verb",
    lemma: "fragen",
    pastParticiple: "gefragt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to ask",
  },
  {
    partOfSpeech: "verb",
    lemma: "einladen",
    pastParticiple: "eingeladen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to invite",
  },
  {
    partOfSpeech: "verb",
    lemma: "ausgehen",
    pastParticiple: "ausgegangen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to go out",
  },
  {
    partOfSpeech: "verb",
    lemma: "daten",
    pastParticiple: "gedatet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to date",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich verabreden",
    pastParticiple: "sich verabredet",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to make a date",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich verlieben",
    pastParticiple: "sich verliebt",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to fall in love",
  },
  {
    partOfSpeech: "verb",
    lemma: "lieben",
    pastParticiple: "geliebt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to love",
  },
  {
    partOfSpeech: "verb",
    lemma: "mögen",
    pastParticiple: "gemocht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to like",
  },
  {
    partOfSpeech: "verb",
    lemma: "genießen",
    pastParticiple: "genossen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to enjoy",
  },
  {
    partOfSpeech: "verb",
    lemma: "verführen",
    pastParticiple: "verführt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to seduce",
  },
];

const sportsAndExerciseVerbs: POSVerb[] = [
  {
    partOfSpeech: "verb",
    lemma: "trainieren",
    pastParticiple: "trainiert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to train",
  },
  {
    partOfSpeech: "verb",
    lemma: "spielen",
    pastParticiple: "gespielt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to play",
  },
  {
    partOfSpeech: "verb",
    lemma: "laufen",
    pastParticiple: "gelaufen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to run",
  },
  {
    partOfSpeech: "verb",
    lemma: "schwimmen",
    pastParticiple: "geschwommen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to swim",
  },
  {
    partOfSpeech: "verb",
    lemma: "springen",
    pastParticiple: "gesprungen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to jump",
  },
  {
    partOfSpeech: "verb",
    lemma: "werfen",
    pastParticiple: "geworfen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to throw",
  },
  {
    partOfSpeech: "verb",
    lemma: "fangen",
    pastParticiple: "gefangen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to catch",
  },
  {
    partOfSpeech: "verb",
    lemma: "schießen",
    pastParticiple: "geschossen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to shoot",
  },
  {
    partOfSpeech: "verb",
    lemma: "klettern",
    pastParticiple: "geklettert",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to climb",
  },
  {
    partOfSpeech: "verb",
    lemma: "fahren",
    pastParticiple: "gefahren",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to drive/ride",
  },
  {
    partOfSpeech: "verb",
    lemma: "reiten",
    pastParticiple: "geritten",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to ride (a horse)",
  },
  {
    partOfSpeech: "verb",
    lemma: "boxen",
    pastParticiple: "geboxt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to box",
  },
  {
    partOfSpeech: "verb",
    lemma: "kämpfen",
    pastParticiple: "gekämpft",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to fight",
  },
  {
    partOfSpeech: "verb",
    lemma: "heben",
    pastParticiple: "gehoben",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to lift",
  },
  {
    partOfSpeech: "verb",
    lemma: "ziehen",
    pastParticiple: "gezogen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pull",
  },
  {
    partOfSpeech: "verb",
    lemma: "stoßen",
    pastParticiple: "gestoßen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to push",
  },
  {
    partOfSpeech: "verb",
    lemma: "dehnen",
    pastParticiple: "gedehnt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to stretch",
  },
  {
    partOfSpeech: "verb",
    lemma: "joggen",
    pastParticiple: "gejoggt",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to jog",
  },
  {
    partOfSpeech: "verb",
    lemma: "wandern",
    pastParticiple: "gewandert",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to hike",
  },
  {
    partOfSpeech: "verb",
    lemma: "radfahren",
    pastParticiple: "radgefahren",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to cycle",
  },
  {
    partOfSpeech: "verb",
    lemma: "skifahren",
    pastParticiple: "skigefahren",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to ski",
  },
  {
    partOfSpeech: "verb",
    lemma: "surfen",
    pastParticiple: "gesurft",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to surf",
  },
  {
    partOfSpeech: "verb",
    lemma: "rudern",
    pastParticiple: "gerudert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to row",
  },
  {
    partOfSpeech: "verb",
    lemma: "segeln",
    pastParticiple: "gesegelt",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to sail",
  },
  {
    partOfSpeech: "verb",
    lemma: "tanzen",
    pastParticiple: "getanzt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to dance",
  },
  {
    partOfSpeech: "verb",
    lemma: "turnen",
    pastParticiple: "geturnt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to do gymnastics",
  },
  {
    partOfSpeech: "verb",
    lemma: "üben",
    pastParticiple: "geübt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to practice",
  },
  {
    partOfSpeech: "verb",
    lemma: "gewinnen",
    pastParticiple: "gewonnen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to win",
  },
  {
    partOfSpeech: "verb",
    lemma: "verlieren",
    pastParticiple: "verloren",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to lose",
  },
  {
    partOfSpeech: "verb",
    lemma: "anfeuern",
    pastParticiple: "angefeuert",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cheer on",
  },
  {
    partOfSpeech: "verb",
    lemma: "aufwärmen",
    pastParticiple: "aufgewärmt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to warm up",
  },
  {
    partOfSpeech: "verb",
    lemma: "dehnen",
    pastParticiple: "gedehnt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to stretch",
  },
  {
    partOfSpeech: "verb",
    lemma: "ausruhen",
    pastParticiple: "ausgeruht",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to rest",
  },
  {
    partOfSpeech: "verb",
    lemma: "atmen",
    pastParticiple: "geatmet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to breathe",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich bewegen",
    pastParticiple: "sich bewegt",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to move",
  },
  {
    partOfSpeech: "verb",
    lemma: "mitmachen",
    pastParticiple: "mitgemacht",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to participate",
  },
  {
    partOfSpeech: "verb",
    lemma: "teilnehmen",
    pastParticiple: "teilgenommen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to take part",
  },
  {
    partOfSpeech: "verb",
    lemma: "starten",
    pastParticiple: "gestartet",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to start",
  },
  {
    partOfSpeech: "verb",
    lemma: "beenden",
    pastParticiple: "beendet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to finish",
  },
  {
    partOfSpeech: "verb",
    lemma: "schlagen",
    pastParticiple: "geschlagen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to hit",
  },
  {
    partOfSpeech: "verb",
    lemma: "treten",
    pastParticiple: "getreten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to kick",
  },
  {
    partOfSpeech: "verb",
    lemma: "zielen",
    pastParticiple: "gezielt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to aim",
  },
  {
    partOfSpeech: "verb",
    lemma: "verteidigen",
    pastParticiple: "verteidigt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to defend",
  },
  {
    partOfSpeech: "verb",
    lemma: "angreifen",
    pastParticiple: "angegriffen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to attack",
  },
  {
    partOfSpeech: "verb",
    lemma: "ausweichen",
    pastParticiple: "ausgewichen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to dodge",
  },
  {
    partOfSpeech: "verb",
    lemma: "konzentrieren",
    pastParticiple: "konzentriert",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to concentrate",
  },
  {
    partOfSpeech: "verb",
    lemma: "motivieren",
    pastParticiple: "motiviert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to motivate",
  },
  {
    partOfSpeech: "verb",
    lemma: "verbessern",
    pastParticiple: "verbessert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to improve",
  },
  {
    partOfSpeech: "verb",
    lemma: "leisten",
    pastParticiple: "geleistet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to perform",
  },
];

const gettingAroundVerbs: POSVerb[] = [
  {
    partOfSpeech: "verb",
    lemma: "gehen",
    pastParticiple: "gegangen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to go",
  },
  {
    partOfSpeech: "verb",
    lemma: "fahren",
    pastParticiple: "gefahren",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to drive",
  },
  {
    partOfSpeech: "verb",
    lemma: "laufen",
    pastParticiple: "gelaufen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to walk/run",
  },
  {
    partOfSpeech: "verb",
    lemma: "fliegen",
    pastParticiple: "geflogen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to fly",
  },
  {
    partOfSpeech: "verb",
    lemma: "reisen",
    pastParticiple: "gereist",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to travel",
  },
  {
    partOfSpeech: "verb",
    lemma: "kommen",
    pastParticiple: "gekommen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to come",
  },
  {
    partOfSpeech: "verb",
    lemma: "abfahren",
    pastParticiple: "abgefahren",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to depart",
  },
  {
    partOfSpeech: "verb",
    lemma: "anfahren",
    pastParticiple: "angefahren",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to arrive",
  },
  {
    partOfSpeech: "verb",
    lemma: "einsteigen",
    pastParticiple: "eingestiegen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to get in/on",
  },
  {
    partOfSpeech: "verb",
    lemma: "aussteigen",
    pastParticiple: "ausgestiegen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to get out/off",
  },
  {
    partOfSpeech: "verb",
    lemma: "umsteigen",
    pastParticiple: "umgestiegen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to change (transport)",
  },
  {
    partOfSpeech: "verb",
    lemma: "steigen",
    pastParticiple: "gestiegen",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to climb",
  },
  {
    partOfSpeech: "verb",
    lemma: "fahren",
    pastParticiple: "gefahren",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to ride",
  },
  {
    partOfSpeech: "verb",
    lemma: "schieben",
    pastParticiple: "geschoben",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to push",
  },
  {
    partOfSpeech: "verb",
    lemma: "ziehen",
    pastParticiple: "gezogen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pull",
  },
  {
    partOfSpeech: "verb",
    lemma: "rollen",
    pastParticiple: "gerollt",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to roll",
  },
  {
    partOfSpeech: "verb",
    lemma: "tragen",
    pastParticiple: "getragen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to carry",
  },
  {
    partOfSpeech: "verb",
    lemma: "bringen",
    pastParticiple: "gebracht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to bring",
  },
  {
    partOfSpeech: "verb",
    lemma: "abholen",
    pastParticiple: "abgeholt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pick up",
  },
  {
    partOfSpeech: "verb",
    lemma: "begleiten",
    pastParticiple: "begleitet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to accompany",
  },
  {
    partOfSpeech: "verb",
    lemma: "verlassen",
    pastParticiple: "verlassen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to leave",
  },
  {
    partOfSpeech: "verb",
    lemma: "erreichen",
    pastParticiple: "erreicht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to reach",
  },
  {
    partOfSpeech: "verb",
    lemma: "sich bewegen",
    pastParticiple: "sich bewegt",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to move",
  },
  {
    partOfSpeech: "verb",
    lemma: "biegen",
    pastParticiple: "gebogen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to turn",
  },
  {
    partOfSpeech: "verb",
    lemma: "wenden",
    pastParticiple: "gewendet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to turn around",
  },
  {
    partOfSpeech: "verb",
    lemma: "abkürzen",
    pastParticiple: "abgekürzt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to shorten",
  },
  {
    partOfSpeech: "verb",
    lemma: "umkehren",
    pastParticiple: "umgekehrt",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to turn back",
  },
  {
    partOfSpeech: "verb",
    lemma: "vorbeigehen",
    pastParticiple: "vorbeigegegangen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to pass by",
  },
  {
    partOfSpeech: "verb",
    lemma: "überqueren",
    pastParticiple: "überquert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cross",
  },
  {
    partOfSpeech: "verb",
    lemma: "verirren",
    pastParticiple: "verirrt",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to get lost",
  },
  {
    partOfSpeech: "verb",
    lemma: "finden",
    pastParticiple: "gefunden",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to find",
  },
  {
    partOfSpeech: "verb",
    lemma: "suchen",
    pastParticiple: "gesucht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to look for",
  },
  {
    partOfSpeech: "verb",
    lemma: "anhalten",
    pastParticiple: "angehalten",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to stop",
  },
  {
    partOfSpeech: "verb",
    lemma: "beschleunigen",
    pastParticiple: "beschleunigt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to accelerate",
  },
  {
    partOfSpeech: "verb",
    lemma: "verlangsamen",
    pastParticiple: "verlangsamt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to slow down",
  },
  {
    partOfSpeech: "verb",
    lemma: "parken",
    pastParticiple: "geparkt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to park",
  },
  {
    partOfSpeech: "verb",
    lemma: "abstellen",
    pastParticiple: "abgestellt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to park/put down",
  },
  {
    partOfSpeech: "verb",
    lemma: "transportieren",
    pastParticiple: "transportiert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to transport",
  },
  {
    partOfSpeech: "verb",
    lemma: "navigieren",
    pastParticiple: "navigiert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to navigate",
  },
  {
    partOfSpeech: "verb",
    lemma: "planen",
    pastParticiple: "geplant",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to plan",
  },
  {
    partOfSpeech: "verb",
    lemma: "reservieren",
    pastParticiple: "reserviert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to reserve",
  },
  {
    partOfSpeech: "verb",
    lemma: "buchen",
    pastParticiple: "gebucht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to book",
  },
  {
    partOfSpeech: "verb",
    lemma: "verspäten",
    pastParticiple: "verspätet",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to be late",
  },
  {
    partOfSpeech: "verb",
    lemma: "beeilen",
    pastParticiple: "beeilt",
    isReflexive: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to hurry",
  },
  {
    partOfSpeech: "verb",
    lemma: "bummeln",
    pastParticiple: "gebummelt",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to stroll",
  },
  {
    partOfSpeech: "verb",
    lemma: "schlendern",
    pastParticiple: "geschlendert",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to saunter",
  },
  {
    partOfSpeech: "verb",
    lemma: "hetzen",
    pastParticiple: "gehetzt",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to rush",
  },
  {
    partOfSpeech: "verb",
    lemma: "gleiten",
    pastParticiple: "geglitten",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to slide",
  },
  {
    partOfSpeech: "verb",
    lemma: "schweben",
    pastParticiple: "geschwebt",
    pastParticipleAuxiliaryVerb: "sein",
    shortEnglishTranslation: "to float",
  },
];

const foodAndDrinkVerbs: POSVerb[] = [
  {
    partOfSpeech: "verb",
    lemma: "essen",
    pastParticiple: "gegessen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to eat",
  },
  {
    partOfSpeech: "verb",
    lemma: "trinken",
    pastParticiple: "getrunken",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to drink",
  },
  {
    partOfSpeech: "verb",
    lemma: "kochen",
    pastParticiple: "gekocht",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cook",
  },
  {
    partOfSpeech: "verb",
    lemma: "backen",
    pastParticiple: "gebacken",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to bake",
  },
  {
    partOfSpeech: "verb",
    lemma: "braten",
    pastParticiple: "gebraten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to fry",
  },
  {
    partOfSpeech: "verb",
    lemma: "schneiden",
    pastParticiple: "geschnitten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cut",
  },
  {
    partOfSpeech: "verb",
    lemma: "schälen",
    pastParticiple: "geschält",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to peel",
  },
  {
    partOfSpeech: "verb",
    lemma: "mischen",
    pastParticiple: "gemischt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to mix",
  },
  {
    partOfSpeech: "verb",
    lemma: "rühren",
    pastParticiple: "gerührt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to stir",
  },
  {
    partOfSpeech: "verb",
    lemma: "hinzufügen",
    pastParticiple: "hinzugefügt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to add",
  },
  {
    partOfSpeech: "verb",
    lemma: "würzen",
    pastParticiple: "gewürzt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to season",
  },
  {
    partOfSpeech: "verb",
    lemma: "salzen",
    pastParticiple: "gesalzen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to salt",
  },
  {
    partOfSpeech: "verb",
    lemma: "pfeffern",
    pastParticiple: "gepfeffert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pepper",
  },
  {
    partOfSpeech: "verb",
    lemma: "erhitzen",
    pastParticiple: "erhitzt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to heat up",
  },
  {
    partOfSpeech: "verb",
    lemma: "kühlen",
    pastParticiple: "gekühlt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cool",
  },
  {
    partOfSpeech: "verb",
    lemma: "servieren",
    pastParticiple: "serviert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to serve",
  },
  {
    partOfSpeech: "verb",
    lemma: "kosten",
    pastParticiple: "gekostet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to taste",
  },
  {
    partOfSpeech: "verb",
    lemma: "riechen",
    pastParticiple: "gerochen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to smell",
  },
  {
    partOfSpeech: "verb",
    lemma: "schmecken",
    pastParticiple: "geschmeckt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to taste",
  },
  {
    partOfSpeech: "verb",
    lemma: "genießen",
    pastParticiple: "genossen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to enjoy",
  },
  {
    partOfSpeech: "verb",
    lemma: "bestellen",
    pastParticiple: "bestellt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to order",
  },
  {
    partOfSpeech: "verb",
    lemma: "zubereiten",
    pastParticiple: "zubereitet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to prepare",
  },
  {
    partOfSpeech: "verb",
    lemma: "verarbeiten",
    pastParticiple: "verarbeitet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to process",
  },
  {
    partOfSpeech: "verb",
    lemma: "lagern",
    pastParticiple: "gelagert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to store",
  },
  {
    partOfSpeech: "verb",
    lemma: "einkaufen",
    pastParticiple: "eingekauft",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to shop",
  },
  {
    partOfSpeech: "verb",
    lemma: "anbauen",
    pastParticiple: "angebaut",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to grow",
  },
  {
    partOfSpeech: "verb",
    lemma: "ernten",
    pastParticiple: "geerntet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to harvest",
  },
  {
    partOfSpeech: "verb",
    lemma: "wiegen",
    pastParticiple: "gewogen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to weigh",
  },
  {
    partOfSpeech: "verb",
    lemma: "abwiegen",
    pastParticiple: "abgewogen",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to weigh out",
  },
  {
    partOfSpeech: "verb",
    lemma: "schneiden",
    pastParticiple: "geschnitten",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cut",
  },
  {
    partOfSpeech: "verb",
    lemma: "zerkleinern",
    pastParticiple: "zerkleinert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to chop",
  },
  {
    partOfSpeech: "verb",
    lemma: "reiben",
    pastParticiple: "gerieben",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to grate",
  },
  {
    partOfSpeech: "verb",
    lemma: "pressen",
    pastParticiple: "gepresst",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to press",
  },
  {
    partOfSpeech: "verb",
    lemma: "gießen",
    pastParticiple: "gegossen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to pour",
  },
  {
    partOfSpeech: "verb",
    lemma: "dämpfen",
    pastParticiple: "gedämpft",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to steam",
  },
  {
    partOfSpeech: "verb",
    lemma: "grillen",
    pastParticiple: "gegrillt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to grill",
  },
  {
    partOfSpeech: "verb",
    lemma: "rösten",
    pastParticiple: "geröstet",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to roast",
  },
  {
    partOfSpeech: "verb",
    lemma: "schmoren",
    pastParticiple: "geschmort",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to braise",
  },
  {
    partOfSpeech: "verb",
    lemma: "marinieren",
    pastParticiple: "mariniert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to marinate",
  },
  {
    partOfSpeech: "verb",
    lemma: "vermischen",
    pastParticiple: "vermischt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to blend",
  },
  {
    partOfSpeech: "verb",
    lemma: "aufwärmen",
    pastParticiple: "aufgewärmt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to warm up",
  },
  {
    partOfSpeech: "verb",
    lemma: "abkühlen",
    pastParticiple: "abgekühlt",
    isSplittable: true,
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to cool down",
  },
  {
    partOfSpeech: "verb",
    lemma: "garnieren",
    pastParticiple: "garniert",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to garnish",
  },
  {
    partOfSpeech: "verb",
    lemma: "schlucken",
    pastParticiple: "geschluckt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to swallow",
  },
  {
    partOfSpeech: "verb",
    lemma: "beißen",
    pastParticiple: "gebissen",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to bite",
  },
  {
    partOfSpeech: "verb",
    lemma: "kauen",
    pastParticiple: "gekaut",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to chew",
  },
  {
    partOfSpeech: "verb",
    lemma: "schlürfen",
    pastParticiple: "geschlürft",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to slurp",
  },
  {
    partOfSpeech: "verb",
    lemma: "verzehren",
    pastParticiple: "verzehrt",
    pastParticipleAuxiliaryVerb: "haben",
    shortEnglishTranslation: "to consume",
  },
];

export const VerbMapping: Record<VocabularyTopics, POSVerb[]> = Object.freeze({
  [VocabularyTopics.GroceryShopping]: shoppingVerbs,
  [VocabularyTopics.Flirting]: flirtingVerbs,
  [VocabularyTopics.SportsAndExercise]: sportsAndExerciseVerbs,
  [VocabularyTopics.GettingAround]: gettingAroundVerbs,
  [VocabularyTopics.FoodAndDrink]: foodAndDrinkVerbs,
});
